spring:
  application:
    name: ChronoVCS
  datasource:
    url: jdbc:postgresql://localhost:5436/chronovcs_db
    username: chronovcs_user
    password: chronovcs_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false
    include-stacktrace: never
    whitelabel:
      enabled: false
chronovcs:
  storage:
    local:
      base-path: /tmp/chronovcs/blobs
  security:
    master-key: ${CHRONOVCS_SECURITY_MASTER_KEY:}
    jwt:
      secret: "VGhpcyBJcyBBIFZlcnkgTG9uZyBBbmQgU2VjdXJlIFNlY3JldCBLZXkgRm9yIENocm9ub1ZDUyBBcHBsaWNhdGlvbiAyMDI1"
      access-ttl-seconds: 900
      refresh-ttl-seconds: 2592000
  cors:
    allowed-origins: ${CHRONOVCS_CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}
    allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
    allowed-headers: "*"
    exposed-headers: Authorization,Content-Type,X-Total-Count
    allow-credentials: true
    max-age: 3600